version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 396057208705.dkr.ecr.eu-west-2.amazonaws.com)
  build:
    commands:
      - docker build -t CP07-youtube-image:latest .
      - docker tag CP07-youtube-image:latest 396057208705.dkr.ecr.eu-west-2.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 396057208705.dkr.ecr.eu-west-2.amazonaws.com/youtube:latest
      - printf '[{"name":"hello-youtube","imageUri":"%s"}]' 396057208705.dkr.ecr.eu-west-2.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
